- 'blockTypeGroup:6efbdc96-00f5-4e37-953b-d36344f6e1fb' # Configured Widgets
- 'blockType:721d7a12-d399-4504-bbeb-0fa6d88d72b7' # Color Filter Tool Block
- 'blockType:430f132d-8145-4e49-ba49-e9b839f7898e' # Source Selector Block
- 'blockType:528d82d4-91db-4ee9-9fa2-8d8c7c871c5e'
