fieldLayouts:
  90215545-5383-4346-a313-278b4d6d52cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: 'For backend reference.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ceea3c75-7352-4c94-a085-f6dd38c10db3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8146cf33-eb0d-46b8-b073-4c100fd3297f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
                  operator: ni
                  uid: fd072f0a-d8c6-4f97-85b8-ad9a61c6958b
                  values:
                    - widget
                    - multiPart
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 919ed98f-d33e-4fae-adc0-2253a155246f # Question Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d27bc2b3-c7ee-4320-8a17-51f542cde29d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
                  operator: in
                  uid: ee8840a7-939c-4dae-915e-e1bd9a10d2c8
                  values:
                    - tabular
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: fcc60644-81ac-4f94-ad34-8bdaeeb4a6b6 # Question Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 447233ea-b878-4183-96be-80710d4a7876
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
                  operator: in
                  uid: feed97bc-9021-4a34-8d76-dc97dc5d50cf
                  values:
                    - widget
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 0fd14cd3-7b23-4230-adce-9cfa16050740 # Widget Instructions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a3037aa-8b7b-4926-8c49-a8932efa7329
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
                  operator: in
                  uid: 27fde6ff-d310-4888-950e-41348fd1bcf1
                  values:
                    - select
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: dffb5cde-7093-4b3c-b9f6-cfc6792ee7a1 # Answer Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd338ce4-5ddc-4368-a5a4-b8de82ae2467
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
                  operator: in
                  uid: a3889d61-666b-4509-96b6-c587e4bb0652
                  values:
                    - widget
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 2599f40c-bfbc-4db6-bf56-cb9f48ad01bf # Question Widgets Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c39f85db-094e-4dcc-901b-227b1dc62550
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
                  operator: in
                  uid: 07e3f34c-8d8c-4e83-bbb2-639db3a48f90
                  values:
                    - multiPart
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 29f139cc-2d9b-4e10-afce-1e6a70105e2b # Multi-part Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0828ed0b-6a98-49fe-acef-63e71708625a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a966d509-84b0-43ab-9a5b-42590a5fb537 # Answer Type
                  operator: in
                  uid: 8ad6bd95-c291-45b9-9fac-4edd4beee636
                  values:
                    - calculator
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e28ed79c-82dd-4c7b-b1cf-abdece40ff5e # Equation
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ddb4a35-2e78-4110-97e9-d1baf7af4260
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38c902fa-7739-496e-a506-0b98d6d480d0
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9068dd8e-ad92-4925-ba1d-1fe180598462 # Questions
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
