fieldLayouts:
  9e8d0324-0d13-49ae-a554-08d2b74185aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bd2bae4a-803c-4218-97d1-5654c604686d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5142c27-2288-47b7-bfad-14cd6b3a6653 # Display Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 552ef0ce-b6b0-4e2a-bb77-513e13f57272
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4afde15-f983-4c30-b0d7-e0b56871e4de # Dataset
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc45dfcd-e889-46fe-8ffb-d27de894632a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 907a99bf-dc51-40c8-8117-c9686eddea0d
            instructions: 'Check to include the light curve scatterplot'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8419c053-d101-476e-bdf4-84634fb53991
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 907a99bf-dc51-40c8-8117-c9686eddea0d
                  uid: 883b118b-023a-4c20-956e-1717464edd26
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 8af07cbd-3ce8-4e4d-818f-261515be5ac7 # Y-axis Minimum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 352316f2-ae0c-42e8-b5d6-329a277e6b8c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 907a99bf-dc51-40c8-8117-c9686eddea0d
                  uid: f3cd8447-372b-4498-a9ca-bfc82a6e12e1
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 61e0fe59-d439-429c-b783-2d71fe4c5d44 # Y-axis Maximum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e1e1d41-ac17-48fa-b435-8428acc2af44
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 897c373a-7e95-45dd-bcb4-8b0d2d51eced
        userCondition: null
handle: sourceSelector
hasTitleField: true
name: 'Source Selector'
section: 28704998-935a-423b-a405-d4ad8b38efa2 # Widgets
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
