columnSuffix: msqfxejh
contentColumnType: string
fieldGroup: b0465285-e18b-4739-a3a5-cb0ec0571dd8 # Questions
handle: answerType
instructions: null
name: 'Answer Type'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Text
        -
          - value
          - text
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Select
        -
          - value
          - select
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Widget
        -
          - value
          - widget
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Textarea
        -
          - value
          - textarea
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Multi-part
        -
          - value
          - multiPart
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Table
        -
          - value
          - tabular
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Calculator
        -
          - value
          - calculator
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
