description: 'Rubin content creators'
handle: editors
name: Editors
permissions:
  - accesscp
  - accessplugin-_canto-dam-assets
  - 'assignusergroup:461e1254-37f7-4aeb-81a1-3f08d2463d06' # Students
  - 'assignusergroup:d8be03ce-7aeb-4141-b40e-ec39ec1c796f' # Educators
  - 'createentries:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'createentries:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'createentries:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'createentries:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'createentries:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'createentries:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'deleteentries:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'deleteentries:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'deleteentries:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'deleteentries:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'deleteentries:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'deleteentries:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'deletepeerentries:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'deletepeerentries:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'deletepeerentries:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'deletepeerentries:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'deletepeerentries:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'deletepeerentries:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'deletepeerentrydrafts:075467b0-0dee-453c-9df0-0de6d2443cf8' # Homepage
  - 'deletepeerentrydrafts:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'deletepeerentrydrafts:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'deletepeerentrydrafts:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'deletepeerentrydrafts:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'deletepeerentrydrafts:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'deletepeerentrydrafts:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'editglobalset:0edce3a2-c596-4238-9dde-212c83d5a65f' # Menu Content
  - 'editglobalset:aee57b4f-2623-44fc-af2b-c670f6e1babe' # Site information
  - 'editsite:2c2e1c6a-eb4d-44f1-9a43-8d79b326f354' # ES
  - 'editsite:356c97b0-54e5-44bb-901e-9d92a314134f' # FR
  - 'editsite:547128fa-4529-4483-9968-66425996b69f' # EN
  - editusers
  - 'neo-createblocks:010dc3f6-c369-4937-adc7-1948204aaf97' # Group
  - 'neo-createblocks:0601483c-a943-42a3-b1a5-e003b05618dc' # Question Block
  - 'neo-createblocks:0d06751e-ecf9-4281-a754-8c818fb9353b' # Color Filter Tool Block
  - 'neo-createblocks:11f12958-c08d-4f26-9466-1a8ba7011b34' # Camera Filter Tool
  - 'neo-createblocks:1ed0caa3-b91f-442b-b313-f3eb54a8a0dc' # Two Column Container
  - 'neo-createblocks:220292c8-0330-4dd4-aa84-f0eeec38fa4e' # Text
  - 'neo-createblocks:28bf8eda-b10b-4aaa-98fd-d52d6c95ef57' # Multiselect
  - 'neo-createblocks:367fe8fa-1963-4fe0-9e02-3c0866c0b5bb' # Color Filter Tool Block
  - 'neo-createblocks:3912a1a0-e71b-44b3-bcf4-976c0564975e' # Filter Tool
  - 'neo-createblocks:485a4230-6aac-41b7-8524-da6232e226ae' # Filter Tool
  - 'neo-createblocks:4e9ea915-78e8-4b28-b44e-fe2af60c77f8' # Image
  - 'neo-createblocks:53df9537-d85e-4fd3-9e4c-b203594ada7c' # Reference Modal Block
  - 'neo-createblocks:5548ce5c-5ad4-494e-93be-8ff129618d20' # Text
  - 'neo-createblocks:59560b67-c194-46fc-9404-cb790a44800a' # Image
  - 'neo-createblocks:5b8a79d6-e9d6-44d2-b986-36bf0bf74131' # Scatterplot Tool
  - 'neo-createblocks:721d7a12-d399-4504-bbeb-0fa6d88d72b7' # Color Filter Tool
  - 'neo-createblocks:7b30c218-6328-41a2-a3e3-2575559f4c9c' # Table
  - 'neo-createblocks:8365851b-c952-499c-84dc-c9e054b83e84' # Select
  - 'neo-createblocks:87fc48a5-a399-4ce1-a7ca-2dadfd1e1445' # Camera Filter Tool
  - 'neo-createblocks:947400f5-3c2d-403a-b94e-68715e48a9c0' # Left Column
  - 'neo-createblocks:9748bbea-73ac-46cc-90b1-e6b8a6da31cd' # Image
  - 'neo-createblocks:a1eeb085-4a92-48ba-92f5-65b9f5ebfc72' # Text
  - 'neo-createblocks:a3f93249-e386-43c7-b2dd-5da2cda1eb03' # Object
  - 'neo-createblocks:a47f94c7-0a32-43be-863a-fa9d6636fff2' # Bar Graph Tool
  - 'neo-createblocks:af9748aa-9a7c-49c2-bf48-d1417664104b' # Text
  - 'neo-createblocks:ba6494d9-36e8-40ee-9284-c56783357043' # Interaction Group
  - 'neo-createblocks:d27f27b6-dfb4-4c6a-9196-ab3c81785d87' # Video
  - 'neo-createblocks:dc1c3484-f028-4653-982b-a84e287d4c61' # Equation
  - 'neo-createblocks:e7b953ca-6424-4d14-bc2c-393d3f8410a4' # Question Text
  - 'neo-createblocks:efbf1b30-4cb7-4361-9f45-016d119aec06' # Right Column
  - 'neo-createblocks:f434501e-30b4-470a-b275-e57e55cadf17' # Source Selector
  - 'neo-createblocks:f4b5a1d9-424f-4bc1-a2ea-37b302b8dc32' # Investigation Grid
  - 'neo-createblocks:f7ef882a-9d5d-4247-9e24-27d4a2702508' # FilterImage
  - 'neo-createblocks:fcfc14fd-28c8-4445-9f56-7c0fe24c0acf' # Table
  - 'neo-deleteblocks:010dc3f6-c369-4937-adc7-1948204aaf97' # Group
  - 'neo-deleteblocks:0601483c-a943-42a3-b1a5-e003b05618dc' # Question Block
  - 'neo-deleteblocks:0d06751e-ecf9-4281-a754-8c818fb9353b' # Color Filter Tool Block
  - 'neo-deleteblocks:11f12958-c08d-4f26-9466-1a8ba7011b34' # Camera Filter Tool
  - 'neo-deleteblocks:1ed0caa3-b91f-442b-b313-f3eb54a8a0dc' # Two Column Container
  - 'neo-deleteblocks:220292c8-0330-4dd4-aa84-f0eeec38fa4e' # Text
  - 'neo-deleteblocks:28bf8eda-b10b-4aaa-98fd-d52d6c95ef57' # Multiselect
  - 'neo-deleteblocks:367fe8fa-1963-4fe0-9e02-3c0866c0b5bb' # Color Filter Tool Block
  - 'neo-deleteblocks:3912a1a0-e71b-44b3-bcf4-976c0564975e' # Filter Tool
  - 'neo-deleteblocks:485a4230-6aac-41b7-8524-da6232e226ae' # Filter Tool
  - 'neo-deleteblocks:4e9ea915-78e8-4b28-b44e-fe2af60c77f8' # Image
  - 'neo-deleteblocks:53df9537-d85e-4fd3-9e4c-b203594ada7c' # Reference Modal Block
  - 'neo-deleteblocks:5548ce5c-5ad4-494e-93be-8ff129618d20' # Text
  - 'neo-deleteblocks:59560b67-c194-46fc-9404-cb790a44800a' # Image
  - 'neo-deleteblocks:5b8a79d6-e9d6-44d2-b986-36bf0bf74131' # Scatterplot Tool
  - 'neo-deleteblocks:721d7a12-d399-4504-bbeb-0fa6d88d72b7' # Color Filter Tool
  - 'neo-deleteblocks:7b30c218-6328-41a2-a3e3-2575559f4c9c' # Table
  - 'neo-deleteblocks:8365851b-c952-499c-84dc-c9e054b83e84' # Select
  - 'neo-deleteblocks:87fc48a5-a399-4ce1-a7ca-2dadfd1e1445' # Camera Filter Tool
  - 'neo-deleteblocks:947400f5-3c2d-403a-b94e-68715e48a9c0' # Left Column
  - 'neo-deleteblocks:9748bbea-73ac-46cc-90b1-e6b8a6da31cd' # Image
  - 'neo-deleteblocks:a1eeb085-4a92-48ba-92f5-65b9f5ebfc72' # Text
  - 'neo-deleteblocks:a3f93249-e386-43c7-b2dd-5da2cda1eb03' # Object
  - 'neo-deleteblocks:a47f94c7-0a32-43be-863a-fa9d6636fff2' # Bar Graph Tool
  - 'neo-deleteblocks:af9748aa-9a7c-49c2-bf48-d1417664104b' # Text
  - 'neo-deleteblocks:ba6494d9-36e8-40ee-9284-c56783357043' # Interaction Group
  - 'neo-deleteblocks:d27f27b6-dfb4-4c6a-9196-ab3c81785d87' # Video
  - 'neo-deleteblocks:dc1c3484-f028-4653-982b-a84e287d4c61' # Equation
  - 'neo-deleteblocks:e7b953ca-6424-4d14-bc2c-393d3f8410a4' # Question Text
  - 'neo-deleteblocks:efbf1b30-4cb7-4361-9f45-016d119aec06' # Right Column
  - 'neo-deleteblocks:f434501e-30b4-470a-b275-e57e55cadf17' # Source Selector
  - 'neo-deleteblocks:f4b5a1d9-424f-4bc1-a2ea-37b302b8dc32' # Investigation Grid
  - 'neo-deleteblocks:f7ef882a-9d5d-4247-9e24-27d4a2702508' # FilterImage
  - 'neo-deleteblocks:fcfc14fd-28c8-4445-9f56-7c0fe24c0acf' # Table
  - 'neo-editblocks:010dc3f6-c369-4937-adc7-1948204aaf97' # Group
  - 'neo-editblocks:0601483c-a943-42a3-b1a5-e003b05618dc' # Question Block
  - 'neo-editblocks:0d06751e-ecf9-4281-a754-8c818fb9353b' # Color Filter Tool Block
  - 'neo-editblocks:11f12958-c08d-4f26-9466-1a8ba7011b34' # Camera Filter Tool
  - 'neo-editblocks:1ed0caa3-b91f-442b-b313-f3eb54a8a0dc' # Two Column Container
  - 'neo-editblocks:220292c8-0330-4dd4-aa84-f0eeec38fa4e' # Text
  - 'neo-editblocks:28bf8eda-b10b-4aaa-98fd-d52d6c95ef57' # Multiselect
  - 'neo-editblocks:367fe8fa-1963-4fe0-9e02-3c0866c0b5bb' # Color Filter Tool Block
  - 'neo-editblocks:3912a1a0-e71b-44b3-bcf4-976c0564975e' # Filter Tool
  - 'neo-editblocks:485a4230-6aac-41b7-8524-da6232e226ae' # Filter Tool
  - 'neo-editblocks:4e9ea915-78e8-4b28-b44e-fe2af60c77f8' # Image
  - 'neo-editblocks:53df9537-d85e-4fd3-9e4c-b203594ada7c' # Reference Modal Block
  - 'neo-editblocks:5548ce5c-5ad4-494e-93be-8ff129618d20' # Text
  - 'neo-editblocks:59560b67-c194-46fc-9404-cb790a44800a' # Image
  - 'neo-editblocks:5b8a79d6-e9d6-44d2-b986-36bf0bf74131' # Scatterplot Tool
  - 'neo-editblocks:721d7a12-d399-4504-bbeb-0fa6d88d72b7' # Color Filter Tool
  - 'neo-editblocks:7b30c218-6328-41a2-a3e3-2575559f4c9c' # Table
  - 'neo-editblocks:8365851b-c952-499c-84dc-c9e054b83e84' # Select
  - 'neo-editblocks:87fc48a5-a399-4ce1-a7ca-2dadfd1e1445' # Camera Filter Tool
  - 'neo-editblocks:947400f5-3c2d-403a-b94e-68715e48a9c0' # Left Column
  - 'neo-editblocks:9748bbea-73ac-46cc-90b1-e6b8a6da31cd' # Image
  - 'neo-editblocks:a1eeb085-4a92-48ba-92f5-65b9f5ebfc72' # Text
  - 'neo-editblocks:a3f93249-e386-43c7-b2dd-5da2cda1eb03' # Object
  - 'neo-editblocks:a47f94c7-0a32-43be-863a-fa9d6636fff2' # Bar Graph Tool
  - 'neo-editblocks:af9748aa-9a7c-49c2-bf48-d1417664104b' # Text
  - 'neo-editblocks:ba6494d9-36e8-40ee-9284-c56783357043' # Interaction Group
  - 'neo-editblocks:d27f27b6-dfb4-4c6a-9196-ab3c81785d87' # Video
  - 'neo-editblocks:dc1c3484-f028-4653-982b-a84e287d4c61' # Equation
  - 'neo-editblocks:e7b953ca-6424-4d14-bc2c-393d3f8410a4' # Question Text
  - 'neo-editblocks:efbf1b30-4cb7-4361-9f45-016d119aec06' # Right Column
  - 'neo-editblocks:f434501e-30b4-470a-b275-e57e55cadf17' # Source Selector
  - 'neo-editblocks:f4b5a1d9-424f-4bc1-a2ea-37b302b8dc32' # Investigation Grid
  - 'neo-editblocks:f7ef882a-9d5d-4247-9e24-27d4a2702508' # FilterImage
  - 'neo-editblocks:fcfc14fd-28c8-4445-9f56-7c0fe24c0acf' # Table
  - registerusers
  - 'saveentries:075467b0-0dee-453c-9df0-0de6d2443cf8' # Homepage
  - 'saveentries:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'saveentries:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'saveentries:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'saveentries:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'saveentries:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'saveentries:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'savepeerentries:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'savepeerentries:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'savepeerentries:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'savepeerentries:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'savepeerentries:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'savepeerentries:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'savepeerentrydrafts:075467b0-0dee-453c-9df0-0de6d2443cf8' # Homepage
  - 'savepeerentrydrafts:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'savepeerentrydrafts:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'savepeerentrydrafts:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'savepeerentrydrafts:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'savepeerentrydrafts:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'savepeerentrydrafts:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'viewentries:075467b0-0dee-453c-9df0-0de6d2443cf8' # Homepage
  - 'viewentries:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'viewentries:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'viewentries:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'viewentries:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'viewentries:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'viewentries:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'viewpeerentries:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'viewpeerentries:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'viewpeerentries:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'viewpeerentries:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'viewpeerentries:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'viewpeerentries:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
  - 'viewpeerentrydrafts:075467b0-0dee-453c-9df0-0de6d2443cf8' # Homepage
  - 'viewpeerentrydrafts:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  - 'viewpeerentrydrafts:28704998-935a-423b-a405-d4ad8b38efa2' # Widgets
  - 'viewpeerentrydrafts:8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d' # Pages
  - 'viewpeerentrydrafts:9068dd8e-ad92-4925-ba1d-1fe180598462' # Questions
  - 'viewpeerentrydrafts:c2356ed1-1e49-4056-83c7-ed615a2694b1' # Reference Modals
  - 'viewpeerentrydrafts:f7b53b4a-8e10-4bda-9c4a-2155c499f214' # Datasets
