childBlocks: null
conditions: null
description: ''
enabled: true
field: 2599f40c-bfbc-4db6-bf56-cb9f48ad01bf # Question Widgets
fieldLayouts:
  9a61a604-e0d2-4bb1-baa3-95eb3213d63d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c904bb15-8e4e-4dfb-964a-841837c4e8ef # Source Selector
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 879d77b8-b0f1-45e6-b13d-46c803a2ebe2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 793a60f9-336c-40f6-b66e-ccf1fa150850
        userCondition: null
group: 6efbdc96-00f5-4e37-953b-d36344f6e1fb # Configured Widgets
groupChildBlockTypes: true
handle: sourceSelector
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Source Selector'
sortOrder: 3
topLevel: true
